### ISSUE TITLE
Over the top server.key encryption?

### ISSUE THREAD

**Issue by chriskl** [forcedotcom/sfdx-bitbucket-package#4]
Seems like it would be easier to go `base64 < server.key` and paste that into a secured Bitbucket Pipeline variable called SERVER_KEY, and then in the pipeline itself go `echo -n $SERVER_KEY | base64 -D > assets/server.key` rather than mucking around with encryption and decryption keys?

**Comment by SamySaied** [comment]
I believe the author did it this way to make it easier to import the key to all required environment and have it stored as part of the repo files instead of in variables. Also having it as a file in the repo makes it easier to fork the repo and start somewhere else, but if you do it with the variable, you will need to setup the variables on the next repo.
